/*
 * Static data: ingredients and recipes. (Countries, regions and shops live in regions.js.)
 *
 * Prices are ESTIMATES in Romanian lei (RON) for one pack, based on typical
 * 2026 supermarket shelf prices. regions.js converts them into each country's
 * currency and price level. Nutrition values are per 100 g (or 100 ml).
 */
(function (g) {
  const MP = (g.MP = g.MP || {});

  // Order in which shop sections appear on the shopping list.
  MP.CATEGORIES = ['produce', 'bakery', 'meat', 'fish', 'dairy', 'frozen', 'pantry', 'spices'];

  // ing(en, ro, category, unit, packSize, packPriceRON, [kcal, protein, carbs, fat] per 100, options)
  // options: g = grams per piece (unit 'pcs'), allergens, animal ('meat'|'fish'|'dairy'|'egg'|'honey'),
  //          staple = pantry basic you usually already have (listed separately, not in the total)
  function ing(en, ro, cat, unit, pack, price, n, o) {
    o = o || {};
    return { name: { en, ro }, cat, unit, pack, price, kcal: n[0], protein: n[1], carbs: n[2], fat: n[3],
      g: o.g || 1, allergens: o.allergens || [], animal: o.animal || null, staple: !!o.staple };
  }

  MP.INGREDIENTS = {
    // produce
    tomato: ing('Tomatoes', 'Roșii', 'produce', 'g', 1000, 9, [18, 0.9, 3.9, 0.2]),
    cucumber: ing('Cucumbers', 'Castraveți', 'produce', 'g', 500, 6, [15, 0.7, 3.6, 0.1]),
    bell_pepper: ing('Bell peppers', 'Ardei gras', 'produce', 'g', 500, 8, [26, 1, 6, 0.3]),
    onion: ing('Onions', 'Ceapă', 'produce', 'g', 1000, 4, [40, 1.1, 9.3, 0.1]),
    garlic: ing('Garlic', 'Usturoi', 'produce', 'g', 100, 3, [149, 6.4, 33, 0.5]),
    carrot: ing('Carrots', 'Morcovi', 'produce', 'g', 1000, 4, [41, 0.9, 9.6, 0.2]),
    potato: ing('Potatoes', 'Cartofi', 'produce', 'g', 2000, 7, [77, 2, 17, 0.1]),
    sweet_potato: ing('Sweet potatoes', 'Cartofi dulci', 'produce', 'g', 1000, 12, [86, 1.6, 20, 0.1]),
    zucchini: ing('Zucchini', 'Dovlecei', 'produce', 'g', 500, 6, [17, 1.2, 3.1, 0.3]),
    eggplant: ing('Eggplants', 'Vinete', 'produce', 'g', 500, 7, [25, 1, 6, 0.2]),
    broccoli: ing('Broccoli', 'Broccoli', 'produce', 'g', 500, 9, [34, 2.8, 7, 0.4]),
    spinach: ing('Baby spinach', 'Spanac baby', 'produce', 'g', 250, 7, [23, 2.9, 3.6, 0.4]),
    lettuce: ing('Lettuce', 'Salată verde', 'produce', 'g', 300, 4, [15, 1.4, 2.9, 0.2]),
    mushrooms: ing('Mushrooms', 'Ciuperci', 'produce', 'g', 500, 9, [22, 3.1, 3.3, 0.3]),
    cabbage: ing('Cabbage', 'Varză albă', 'produce', 'g', 1500, 5, [25, 1.3, 5.8, 0.1]),
    lemon: ing('Lemons', 'Lămâi', 'produce', 'g', 500, 6, [29, 1.1, 9, 0.3]),
    avocado: ing('Avocado', 'Avocado', 'produce', 'pcs', 1, 5, [160, 2, 9, 15], { g: 150 }),
    banana: ing('Bananas', 'Banane', 'produce', 'g', 1000, 7, [89, 1.1, 23, 0.3]),
    apple: ing('Apples', 'Mere', 'produce', 'g', 1000, 6, [52, 0.3, 14, 0.2]),
    parsley: ing('Parsley (bunch)', 'Pătrunjel (legătură)', 'produce', 'g', 50, 2, [36, 3, 6, 0.8]),
    dill: ing('Dill (bunch)', 'Mărar (legătură)', 'produce', 'g', 50, 2, [43, 3.5, 7, 1.1]),
    green_onion: ing('Spring onions', 'Ceapă verde', 'produce', 'g', 100, 2, [32, 1.8, 7, 0.2]),
    chili: ing('Hot chili peppers', 'Ardei iute', 'produce', 'g', 100, 3, [40, 2, 9, 0.4]),
    // bakery
    bread: ing('Wholegrain bread', 'Pâine integrală', 'bakery', 'g', 500, 7, [247, 13, 41, 3.4], { allergens: ['gluten'] }),
    tortilla: ing('Wholewheat tortillas', 'Lipii integrale', 'bakery', 'pcs', 6, 9, [300, 8, 50, 7], { g: 60, allergens: ['gluten'] }),
    // meat
    chicken_breast: ing('Chicken breast', 'Piept de pui', 'meat', 'g', 1000, 30, [120, 23, 0, 2.6], { animal: 'meat' }),
    chicken_thigh: ing('Boneless chicken thighs', 'Pulpe de pui dezosate', 'meat', 'g', 1000, 25, [177, 18, 0, 11], { animal: 'meat' }),
    ground_beef: ing('Ground beef', 'Carne tocată de vită', 'meat', 'g', 500, 25, [250, 17, 0, 20], { animal: 'meat', allergens: ['beef'] }),
    ground_turkey: ing('Ground turkey', 'Carne tocată de curcan', 'meat', 'g', 500, 22, [150, 20, 0, 8], { animal: 'meat' }),
    // fish
    salmon: ing('Salmon fillet', 'File de somon', 'fish', 'g', 250, 25, [208, 20, 0, 13], { allergens: ['fish'], animal: 'fish' }),
    white_fish: ing('White fish fillet (hake/cod)', 'File de pește alb (merluciu/cod)', 'frozen', 'g', 500, 22, [82, 18, 0, 0.7], { allergens: ['fish'], animal: 'fish' }),
    tuna_can: ing('Tuna in water (can)', 'Ton în suc propriu (conservă)', 'pantry', 'g', 120, 7, [116, 26, 0, 1], { allergens: ['fish'], animal: 'fish' }),
    // dairy & eggs
    eggs: ing('Eggs', 'Ouă', 'dairy', 'pcs', 10, 10, [143, 12.6, 0.7, 9.5], { g: 55, allergens: ['egg'], animal: 'egg' }),
    milk: ing('Milk 1.5%', 'Lapte 1,5%', 'dairy', 'ml', 1000, 7, [46, 3.4, 4.8, 1.5], { allergens: ['dairy'], animal: 'dairy' }),
    oat_drink: ing('Oat drink', 'Băutură de ovăz', 'dairy', 'ml', 1000, 12, [45, 1, 7, 1.5], { allergens: ['gluten'] }),
    greek_yogurt: ing('Greek yogurt', 'Iaurt grecesc', 'dairy', 'g', 400, 9, [97, 9, 4, 5], { allergens: ['dairy'], animal: 'dairy' }),
    telemea: ing('Telemea / feta cheese', 'Telemea', 'dairy', 'g', 400, 14, [260, 17, 1, 21], { allergens: ['dairy'], animal: 'dairy' }),
    cottage: ing('Cottage cheese', 'Brânză de vaci', 'dairy', 'g', 250, 7, [98, 11, 3.4, 4.3], { allergens: ['dairy'], animal: 'dairy' }),
    parmesan: ing('Parmesan', 'Parmezan', 'dairy', 'g', 100, 10, [431, 38, 4, 29], { allergens: ['dairy'], animal: 'dairy' }),
    sour_cream: ing('Sour cream', 'Smântână', 'dairy', 'g', 200, 5, [193, 2.4, 3.5, 19], { allergens: ['dairy'], animal: 'dairy' }),
    tofu: ing('Tofu', 'Tofu', 'dairy', 'g', 200, 8, [144, 15, 3, 8.7], { allergens: ['soy'] }),
    hummus: ing('Hummus', 'Hummus', 'dairy', 'g', 200, 7, [177, 8, 14, 10], { allergens: ['sesame'] }),
    // frozen
    berries: ing('Frozen mixed berries', 'Fructe de pădure congelate', 'frozen', 'g', 500, 15, [50, 0.7, 12, 0.3]),
    green_peas: ing('Frozen green peas', 'Mazăre congelată', 'frozen', 'g', 1000, 10, [81, 5.4, 14, 0.4]),
    // pantry
    oats: ing('Rolled oats', 'Fulgi de ovăz', 'pantry', 'g', 500, 5, [379, 13, 68, 6.5], { allergens: ['gluten'] }),
    rice: ing('Rice', 'Orez', 'pantry', 'g', 1000, 8, [360, 7, 79, 0.6]),
    pasta: ing('Wholewheat pasta', 'Paste integrale', 'pantry', 'g', 500, 6, [350, 13, 68, 2.5], { allergens: ['gluten'] }),
    quinoa: ing('Quinoa', 'Quinoa', 'pantry', 'g', 500, 15, [368, 14, 64, 6]),
    cornmeal: ing('Cornmeal', 'Mălai', 'pantry', 'g', 1000, 5, [362, 8, 77, 3.6]),
    lentils: ing('Red lentils', 'Linte roșie', 'pantry', 'g', 500, 8, [358, 24, 60, 2]),
    white_beans: ing('Dried white beans', 'Fasole albă boabe', 'pantry', 'g', 500, 8, [333, 23, 60, 0.9]),
    chickpeas: ing('Chickpeas (can, drained)', 'Năut (conservă, scurs)', 'pantry', 'g', 240, 5, [139, 7, 22, 2.6]),
    red_beans: ing('Red kidney beans (can, drained)', 'Fasole roșie (conservă, scursă)', 'pantry', 'g', 240, 5, [127, 8.7, 22, 0.5]),
    tomato_can: ing('Chopped tomatoes (can)', 'Roșii tăiate (conservă)', 'pantry', 'g', 400, 4, [32, 1.6, 5, 0.3]),
    tomato_paste: ing('Tomato paste', 'Pastă de tomate', 'pantry', 'g', 140, 3, [82, 4.3, 19, 0.5]),
    coconut_milk: ing('Coconut milk', 'Lapte de cocos', 'pantry', 'ml', 400, 8, [197, 2, 3, 21]),
    olives: ing('Olives', 'Măsline', 'pantry', 'g', 200, 9, [115, 0.8, 6, 11]),
    peanut_butter: ing('Peanut butter', 'Unt de arahide', 'pantry', 'g', 350, 14, [588, 25, 20, 50], { allergens: ['peanuts'] }),
    walnuts: ing('Walnuts', 'Miez de nucă', 'pantry', 'g', 200, 16, [654, 15, 14, 65], { allergens: ['treenuts'] }),
    almonds: ing('Almonds', 'Migdale', 'pantry', 'g', 200, 15, [579, 21, 22, 50], { allergens: ['treenuts'] }),
    chia: ing('Chia seeds', 'Semințe de chia', 'pantry', 'g', 200, 10, [486, 17, 42, 31]),
    honey: ing('Honey', 'Miere', 'pantry', 'g', 400, 20, [304, 0.3, 82, 0], { animal: 'honey' }),
    // world-cuisine ingredients
    ginger: ing('Fresh ginger', 'Ghimbir proaspăt', 'produce', 'g', 100, 3, [80, 1.8, 18, 0.8]),
    cilantro: ing('Fresh coriander (bunch)', 'Coriandru verde (legătură)', 'produce', 'g', 50, 3, [23, 2.1, 3.7, 0.5]),
    lime: ing('Limes', 'Lime', 'produce', 'g', 500, 9, [30, 0.7, 10.5, 0.2]),
    kale: ing('Kale / collard greens', 'Kale (varză furajeră)', 'produce', 'g', 250, 8, [49, 4.3, 8.8, 0.9]),
    plantain: ing('Plantains', 'Banane plantain', 'produce', 'g', 1000, 15, [122, 1.3, 32, 0.4]),
    sweet_corn: ing('Sweet corn (frozen)', 'Porumb dulce congelat', 'frozen', 'g', 450, 7, [86, 3.3, 19, 1.4]),
    shrimp: ing('Frozen shrimp', 'Creveți congelați', 'frozen', 'g', 400, 30, [99, 24, 0.2, 0.3], { allergens: ['shellfish'], animal: 'fish' }),
    paneer: ing('Paneer', 'Paneer (brânză indiană)', 'dairy', 'g', 200, 12, [321, 21, 3.6, 25], { allergens: ['dairy'], animal: 'dairy' }),
    cheddar: ing('Cheddar cheese', 'Brânză cheddar', 'dairy', 'g', 200, 10, [403, 25, 1.3, 33], { allergens: ['dairy'], animal: 'dairy' }),
    tortilla_corn: ing('Corn tortillas', 'Tortilla din porumb', 'bakery', 'pcs', 10, 10, [218, 5.7, 45, 2.9], { g: 30 }),
    pita: ing('Pita bread', 'Lipie pita', 'bakery', 'pcs', 4, 6, [275, 9, 55, 1.2], { g: 70, allergens: ['gluten'] }),
    rice_noodles: ing('Rice noodles', 'Tăiței de orez', 'pantry', 'g', 400, 9, [364, 6, 80, 0.6]),
    couscous: ing('Couscous', 'Cuscus', 'pantry', 'g', 500, 7, [376, 13, 77, 0.6], { allergens: ['gluten'] }),
    black_beans: ing('Black beans (can, drained)', 'Fasole neagră (conservă, scursă)', 'pantry', 'g', 240, 6, [132, 8.9, 24, 0.5]),
    tahini: ing('Tahini', 'Tahini (pastă de susan)', 'pantry', 'g', 300, 15, [595, 17, 21, 54], { allergens: ['sesame'] }),
    miso: ing('Miso paste', 'Pastă miso', 'pantry', 'g', 300, 18, [199, 12, 26, 6], { allergens: ['soy'] }),
    gochujang: ing('Gochujang chili paste', 'Pastă de ardei gochujang', 'pantry', 'g', 200, 15, [200, 4, 40, 2], { allergens: ['soy', 'gluten'] }),
    curry_paste: ing('Thai red curry paste (vegan)', 'Pastă de curry roșu thailandez (vegană)', 'pantry', 'g', 100, 8, [150, 3, 15, 8]),
    peanuts: ing('Roasted peanuts', 'Arahide prăjite', 'pantry', 'g', 200, 7, [585, 24, 21, 50], { allergens: ['peanuts'] }),
    // staples (assumed in your pantry; listed separately)
    olive_oil: ing('Olive oil', 'Ulei de măsline', 'pantry', 'ml', 500, 30, [884, 0, 0, 100], { staple: true }),
    butter: ing('Butter', 'Unt', 'dairy', 'g', 200, 10, [717, 0.9, 0.1, 81], { allergens: ['dairy'], animal: 'dairy', staple: true }),
    soy_sauce: ing('Soy sauce', 'Sos de soia', 'pantry', 'ml', 150, 6, [53, 8, 5, 0.6], { allergens: ['soy', 'gluten'], staple: true }),
    stock_cube: ing('Vegetable stock cube', 'Cub de supă de legume', 'pantry', 'pcs', 8, 5, [250, 10, 30, 10], { g: 10, staple: true }),
    paprika: ing('Sweet paprika', 'Boia dulce', 'spices', 'g', 50, 4, [282, 14, 54, 13], { staple: true }),
    cumin: ing('Ground cumin', 'Chimion măcinat', 'spices', 'g', 30, 4, [375, 18, 44, 22], { staple: true }),
    curry: ing('Curry powder', 'Curry', 'spices', 'g', 30, 4, [325, 14, 58, 14], { staple: true }),
    oregano: ing('Dried oregano', 'Oregano uscat', 'spices', 'g', 10, 3, [265, 9, 69, 4], { staple: true }),
    chili_flakes: ing('Chili flakes', 'Fulgi de ardei iute', 'spices', 'g', 30, 4, [282, 12, 50, 14], { staple: true }),
    sesame_oil: ing('Sesame oil', 'Ulei de susan', 'pantry', 'ml', 250, 15, [884, 0, 0, 100], { allergens: ['sesame'], staple: true }),
    garam_masala: ing('Garam masala', 'Garam masala', 'spices', 'g', 50, 5, [379, 15, 45, 15], { staple: true }),
    turmeric: ing('Ground turmeric', 'Turmeric (curcuma)', 'spices', 'g', 50, 4, [312, 10, 67, 3], { staple: true }),
    cinnamon: ing('Ground cinnamon', 'Scorțișoară', 'spices', 'g', 30, 4, [247, 4, 81, 1.2], { staple: true }),
  };

  // Recipe ingredients are [ingredientId, quantity per serving, 'side'?].
  // 'side' marks a carb side (rice, bread, mămăligă...) that is left out for low-carb / keto eaters.
  // meal: 'breakfast' | 'main' (lunch or dinner) | 'snack'
  // cuisine: one of MP.CUISINES (below); 'international' recipes are suggested to everyone
  // tags: spicy, quick, comfort, fresh, romanian, mediterranean, sweet, batch
  MP.RECIPES = [
    // ───── breakfast ─────
    { id: 'overnight_oats', cuisine: 'international', emoji: '🥣', meal: ['breakfast'], time: 5, tags: ['quick', 'sweet'],
      name: { en: 'Overnight oats with berries', ro: 'Ovăz peste noapte cu fructe de pădure' },
      ing: [['oats', 50], ['milk', 150], ['chia', 10], ['berries', 80], ['honey', 10]],
      steps: { en: ['Mix oats, chia and milk in a jar.', 'Top with berries and honey.', 'Refrigerate overnight and eat cold.'],
        ro: ['Amestecă ovăzul, chia și laptele într-un borcan.', 'Pune deasupra fructele și mierea.', 'Lasă la frigider peste noapte și servește rece.'] } },
    { id: 'yogurt_bowl', cuisine: 'international', emoji: '🍓', meal: ['breakfast'], time: 5, tags: ['quick', 'sweet'],
      name: { en: 'Greek yogurt bowl with walnuts', ro: 'Bol cu iaurt grecesc și nuci' },
      ing: [['greek_yogurt', 200], ['berries', 80], ['walnuts', 15], ['honey', 10]],
      steps: { en: ['Spoon yogurt into a bowl.', 'Add thawed berries, chopped walnuts and a drizzle of honey.'],
        ro: ['Pune iaurtul într-un bol.', 'Adaugă fructele decongelate, nucile tocate și puțină miere.'] } },
    { id: 'veggie_omelette', cuisine: 'international', emoji: '🍳', meal: ['breakfast'], time: 10, tags: ['quick'],
      name: { en: 'Spinach & mushroom omelette with telemea', ro: 'Omletă cu spanac, ciuperci și telemea' },
      ing: [['eggs', 2], ['spinach', 40], ['mushrooms', 60], ['telemea', 30], ['olive_oil', 5], ['bread', 40, 'side']],
      steps: { en: ['Sauté sliced mushrooms in oil for 3 minutes, add spinach until wilted.', 'Pour in beaten eggs, crumble telemea on top.', 'Cook on low heat until set. Serve with bread.'],
        ro: ['Călește ciupercile feliate 3 minute, adaugă spanacul până se înmoaie.', 'Toarnă ouăle bătute și sfărâmă telemeaua deasupra.', 'Gătește la foc mic până se închega. Servește cu pâine.'] } },
    { id: 'avocado_toast', cuisine: 'western', emoji: '🥑', meal: ['breakfast'], time: 10, tags: ['quick', 'fresh'],
      name: { en: 'Avocado toast with a fried egg', ro: 'Pâine prăjită cu avocado și ou' },
      ing: [['bread', 70], ['avocado', 0.5], ['eggs', 1], ['lemon', 10], ['chili_flakes', 0.5]],
      steps: { en: ['Toast the bread.', 'Mash avocado with lemon juice, salt and chili flakes.', 'Spread on toast and top with a fried egg.'],
        ro: ['Prăjește pâinea.', 'Zdrobește avocado cu zeamă de lămâie, sare și fulgi de ardei.', 'Unge pâinea și pune deasupra un ou ochi.'] } },
    { id: 'branza_smantana', cuisine: 'eastern_european', emoji: '🧀', meal: ['breakfast'], time: 5, tags: ['quick', 'romanian', 'fresh'],
      name: { en: 'Cottage cheese with sour cream, dill & tomatoes', ro: 'Brânză de vaci cu smântână, mărar și roșii' },
      ing: [['cottage', 150], ['sour_cream', 30], ['dill', 5], ['green_onion', 15], ['tomato', 120], ['bread', 50, 'side']],
      steps: { en: ['Mix cottage cheese with sour cream, chopped dill and spring onion.', 'Season with salt and pepper.', 'Serve with sliced tomatoes and bread.'],
        ro: ['Amestecă brânza cu smântâna, mărarul și ceapa verde tocate.', 'Condimentează cu sare și piper.', 'Servește cu roșii feliate și pâine.'] } },
    { id: 'shakshuka', cuisine: 'middle_eastern', emoji: '🍅', meal: ['breakfast', 'main'], time: 25, tags: ['spicy', 'mediterranean'],
      name: { en: 'Shakshuka', ro: 'Shakshuka (ouă în sos de roșii)' },
      ing: [['eggs', 2], ['tomato_can', 200], ['bell_pepper', 80], ['onion', 50], ['garlic', 5], ['paprika', 2], ['cumin', 1], ['olive_oil', 7], ['bread', 40, 'side']],
      steps: { en: ['Soften onion and pepper in oil, add garlic, paprika and cumin.', 'Add tomatoes and simmer 10 minutes.', 'Make wells, crack in the eggs, cover and cook 5–7 minutes.', 'Serve with bread.'],
        ro: ['Călește ceapa și ardeiul, adaugă usturoiul, boiaua și chimionul.', 'Adaugă roșiile și fierbe 10 minute.', 'Fă adâncituri, sparge ouăle, acoperă și gătește 5–7 minute.', 'Servește cu pâine.'] } },
    { id: 'pb_banana_oats', cuisine: 'western', emoji: '🍌', meal: ['breakfast'], time: 10, tags: ['quick', 'sweet', 'comfort'],
      name: { en: 'Peanut butter banana porridge', ro: 'Terci de ovăz cu banană și unt de arahide' },
      ing: [['oats', 60], ['oat_drink', 200], ['banana', 100], ['peanut_butter', 15]],
      steps: { en: ['Simmer oats in oat drink for 5 minutes, stirring.', 'Top with sliced banana and peanut butter.'],
        ro: ['Fierbe ovăzul în băutura de ovăz 5 minute, amestecând.', 'Pune deasupra banana feliată și untul de arahide.'] } },
    { id: 'tofu_scramble', cuisine: 'international', emoji: '🌱', meal: ['breakfast'], time: 15, tags: ['quick'],
      name: { en: 'Tofu scramble with spinach', ro: 'Tofu „jumări” cu spanac' },
      ing: [['tofu', 150], ['spinach', 40], ['tomato', 80], ['onion', 30], ['curry', 1], ['olive_oil', 7], ['bread', 50, 'side']],
      steps: { en: ['Fry chopped onion in oil, crumble in the tofu and curry powder.', 'Add diced tomato and spinach and cook 3 minutes.', 'Season and serve with bread.'],
        ro: ['Călește ceapa, sfărâmă tofu și adaugă curry.', 'Adaugă roșia tăiată și spanacul, gătește 3 minute.', 'Condimentează și servește cu pâine.'] } },
    { id: 'chia_pudding', cuisine: 'international', emoji: '🥥', meal: ['breakfast'], time: 5, tags: ['quick', 'sweet'],
      name: { en: 'Coconut chia pudding', ro: 'Budincă de chia cu cocos' },
      ing: [['chia', 30], ['coconut_milk', 120], ['berries', 50], ['almonds', 10]],
      steps: { en: ['Stir chia into coconut milk with 50 ml water.', 'Refrigerate at least 4 hours.', 'Top with berries and chopped almonds.'],
        ro: ['Amestecă chia cu laptele de cocos și 50 ml apă.', 'Lasă la frigider minim 4 ore.', 'Pune deasupra fructe și migdale tocate.'] } },
    { id: 'smoothie_bowl', cuisine: 'international', emoji: '🍇', meal: ['breakfast'], time: 5, tags: ['quick', 'sweet', 'fresh'],
      name: { en: 'Berry & banana smoothie bowl', ro: 'Smoothie bowl cu fructe de pădure și banană' },
      ing: [['banana', 120], ['berries', 120], ['coconut_milk', 60], ['chia', 15], ['almonds', 15]],
      steps: { en: ['Blend banana, frozen berries and coconut milk until thick.', 'Pour into a bowl and top with chia and chopped almonds.'],
        ro: ['Mixează banana, fructele congelate și laptele de cocos până devine cremos.', 'Toarnă într-un bol și presară chia și migdale tocate.'] } },
    { id: 'mamaliga_branza', cuisine: 'eastern_european', emoji: '🌽', meal: ['breakfast', 'main'], time: 25, tags: ['romanian', 'comfort'],
      name: { en: 'Mămăligă with telemea, sour cream & egg', ro: 'Mămăligă cu brânză, smântână și ou' },
      ing: [['cornmeal', 70], ['telemea', 40], ['sour_cream', 30], ['eggs', 1]],
      steps: { en: ['Bring 300 ml salted water to the boil, whisk in cornmeal.', 'Cook 15 minutes on low heat, stirring.', 'Serve with crumbled telemea, sour cream and a fried egg.'],
        ro: ['Fierbe 300 ml apă cu sare, adaugă mălaiul în ploaie amestecând.', 'Gătește 15 minute la foc mic, amestecând.', 'Servește cu telemea, smântână și un ou ochi.'] } },

    // ───── lunch & dinner ─────
    { id: 'spicy_chicken_stirfry', cuisine: 'chinese', emoji: '🌶️', meal: ['main'], time: 25, tags: ['spicy', 'quick'],
      name: { en: 'Spicy chicken stir-fry with rice', ro: 'Pui picant la wok cu orez' },
      ing: [['chicken_breast', 150], ['bell_pepper', 100], ['broccoli', 100], ['green_onion', 15], ['garlic', 5], ['chili', 10], ['soy_sauce', 15], ['olive_oil', 10], ['rice', 70, 'side']],
      steps: { en: ['Cook the rice.', 'Stir-fry chicken strips in hot oil until golden.', 'Add peppers, broccoli, garlic and chili; cook 4 minutes.', 'Add soy sauce and spring onion. Serve over rice.'],
        ro: ['Fierbe orezul.', 'Prăjește fâșiile de pui în ulei încins până se rumenesc.', 'Adaugă ardeiul, broccoli, usturoiul și ardeiul iute; gătește 4 minute.', 'Adaugă sosul de soia și ceapa verde. Servește cu orez.'] } },
    { id: 'chicken_traybake', cuisine: 'western', emoji: '🍗', meal: ['main'], time: 50, tags: ['comfort', 'romanian'],
      name: { en: 'Chicken thighs with oven-roasted vegetables', ro: 'Pulpe de pui la cuptor cu legume' },
      ing: [['chicken_thigh', 180], ['potato', 200, 'side'], ['carrot', 100], ['onion', 50], ['garlic', 5], ['paprika', 2], ['olive_oil', 10]],
      steps: { en: ['Heat oven to 200 °C.', 'Toss chicken and chopped vegetables with oil, paprika, garlic and salt.', 'Roast 40 minutes, turning halfway.'],
        ro: ['Încinge cuptorul la 200 °C.', 'Amestecă puiul și legumele tăiate cu ulei, boia, usturoi și sare.', 'Coace 40 de minute, întorcând la jumătate.'] } },
    { id: 'ciorba_legume', cuisine: 'eastern_european', emoji: '🍲', meal: ['main'], time: 45, tags: ['romanian', 'comfort', 'batch'],
      name: { en: 'Romanian vegetable sour soup', ro: 'Ciorbă de legume' },
      ing: [['potato', 100], ['carrot', 70], ['onion', 50], ['bell_pepper', 50], ['green_peas', 50], ['zucchini', 80], ['tomato_can', 100], ['stock_cube', 0.25], ['parsley', 5], ['lemon', 15], ['bread', 60, 'side']],
      steps: { en: ['Chop all vegetables.', 'Boil onion, carrot and potato in 500 ml water per serving with the stock cube for 15 minutes.', 'Add pepper, zucchini, peas and tomatoes; simmer 15 minutes.', 'Sour with lemon juice, add parsley. Serve with bread.'],
        ro: ['Taie toate legumele.', 'Fierbe ceapa, morcovul și cartoful în 500 ml apă/porție cu cubul de supă, 15 minute.', 'Adaugă ardeiul, dovleceii, mazărea și roșiile; fierbe 15 minute.', 'Acrește cu zeamă de lămâie și adaugă pătrunjel. Servește cu pâine.'] } },
    { id: 'lentil_curry', cuisine: 'indian', emoji: '🍛', meal: ['main'], time: 30, tags: ['spicy', 'batch', 'comfort'],
      name: { en: 'Red lentil & spinach curry', ro: 'Curry de linte roșie cu spanac' },
      ing: [['lentils', 70], ['coconut_milk', 70], ['tomato_can', 150], ['onion', 60], ['garlic', 5], ['curry', 3], ['spinach', 50], ['olive_oil', 5], ['rice', 50, 'side']],
      steps: { en: ['Soften onion and garlic in oil, add curry powder.', 'Add lentils, tomatoes, coconut milk and 150 ml water per serving.', 'Simmer 20 minutes, stir in spinach.', 'Serve with rice.'],
        ro: ['Călește ceapa și usturoiul, adaugă curry.', 'Adaugă lintea, roșiile, laptele de cocos și 150 ml apă/porție.', 'Fierbe 20 de minute, adaugă spanacul.', 'Servește cu orez.'] } },
    { id: 'greek_salad_chicken', cuisine: 'mediterranean', emoji: '🥗', meal: ['main'], time: 20, tags: ['fresh', 'mediterranean', 'quick'],
      name: { en: 'Greek salad with grilled chicken', ro: 'Salată grecească cu pui la grătar' },
      ing: [['chicken_breast', 130], ['tomato', 150], ['cucumber', 120], ['bell_pepper', 50], ['onion', 20], ['telemea', 50], ['olives', 30], ['olive_oil', 10], ['oregano', 1]],
      steps: { en: ['Season and grill the chicken, then slice.', 'Chop tomatoes, cucumber, pepper and onion.', 'Top with telemea, olives, oregano and olive oil.'],
        ro: ['Condimentează și fă puiul la grătar, apoi feliază-l.', 'Taie roșiile, castravetele, ardeiul și ceapa.', 'Adaugă telemea, măsline, oregano și ulei de măsline.'] } },
    { id: 'salmon_broccoli', cuisine: 'western', emoji: '🐟', meal: ['main'], time: 25, tags: ['quick', 'mediterranean'],
      name: { en: 'Lemon garlic salmon with broccoli', ro: 'Somon cu lămâie, usturoi și broccoli' },
      ing: [['salmon', 150], ['broccoli', 200], ['lemon', 20], ['garlic', 5], ['olive_oil', 10], ['quinoa', 50, 'side']],
      steps: { en: ['Heat oven to 200 °C. Cook the quinoa.', 'Place salmon and broccoli on a tray, drizzle with oil, garlic and lemon.', 'Bake 15 minutes.'],
        ro: ['Încinge cuptorul la 200 °C. Fierbe quinoa.', 'Pune somonul și broccoli în tavă, stropește cu ulei, usturoi și lămâie.', 'Coace 15 minute.'] } },
    { id: 'fish_potatoes', cuisine: 'mediterranean', emoji: '🐠', meal: ['main'], time: 40, tags: ['mediterranean', 'romanian'],
      name: { en: 'Baked white fish with dill potatoes', ro: 'Pește alb la cuptor cu cartofi cu mărar' },
      ing: [['white_fish', 180], ['potato', 250, 'side'], ['lemon', 20], ['dill', 5], ['garlic', 5], ['olive_oil', 10], ['cucumber', 100]],
      steps: { en: ['Boil the potatoes for 15 minutes.', 'Bake the fish with oil, garlic and lemon at 200 °C for 15 minutes.', 'Toss potatoes with dill. Serve with cucumber salad.'],
        ro: ['Fierbe cartofii 15 minute.', 'Coace peștele cu ulei, usturoi și lămâie la 200 °C, 15 minute.', 'Amestecă cartofii cu mărar. Servește cu salată de castraveți.'] } },
    { id: 'turkey_meatballs', cuisine: 'italian', emoji: '🧆', meal: ['main'], time: 35, tags: ['comfort', 'batch'],
      name: { en: 'Turkey meatballs in tomato sauce with zucchini noodles', ro: 'Chiftele de curcan în sos de roșii cu tăiței de dovlecel' },
      ing: [['ground_turkey', 150], ['eggs', 0.25], ['parsley', 5], ['onion', 40], ['garlic', 5], ['tomato_can', 150], ['zucchini', 200], ['parmesan', 10], ['olive_oil', 5]],
      steps: { en: ['Mix turkey, egg, parsley, half the onion and garlic; shape small balls.', 'Brown the meatballs, add remaining onion and tomatoes; simmer 15 minutes.', 'Spiralize or thinly slice zucchini and sauté 2 minutes.', 'Serve topped with parmesan.'],
        ro: ['Amestecă carnea, oul, pătrunjelul, jumătate din ceapă și usturoi; formează chiftele mici.', 'Rumenește chiftelele, adaugă restul de ceapă și roșiile; fierbe 15 minute.', 'Taie dovleceii fâșii subțiri și călește-i 2 minute.', 'Servește cu parmezan.'] } },
    { id: 'pasta_bolognese', cuisine: 'italian', emoji: '🍝', meal: ['main'], time: 35, tags: ['comfort', 'batch'],
      name: { en: 'Wholewheat pasta bolognese', ro: 'Paste integrale bolognese' },
      ing: [['ground_beef', 120], ['onion', 50], ['carrot', 50], ['garlic', 5], ['tomato_can', 150], ['olive_oil', 5], ['parmesan', 10], ['pasta', 90, 'side']],
      steps: { en: ['Brown the beef with onion, carrot and garlic.', 'Add tomatoes and simmer 20 minutes.', 'Cook the pasta and serve with the sauce and parmesan.'],
        ro: ['Rumenește carnea cu ceapa, morcovul și usturoiul.', 'Adaugă roșiile și fierbe 20 de minute.', 'Fierbe pastele și servește cu sosul și parmezan.'] } },
    { id: 'chili_con_carne', cuisine: 'latin', emoji: '🔥', meal: ['main'], time: 40, tags: ['spicy', 'batch', 'comfort'],
      name: { en: 'Chili con carne', ro: 'Chili con carne' },
      ing: [['ground_beef', 120], ['red_beans', 120], ['tomato_can', 150], ['onion', 50], ['bell_pepper', 70], ['chili', 5], ['cumin', 2], ['paprika', 2], ['rice', 60, 'side']],
      steps: { en: ['Brown beef with onion and pepper.', 'Add spices, chili, tomatoes and beans.', 'Simmer 25 minutes. Serve with rice.'],
        ro: ['Rumenește carnea cu ceapa și ardeiul.', 'Adaugă condimentele, ardeiul iute, roșiile și fasolea.', 'Fierbe 25 de minute. Servește cu orez.'] } },
    { id: 'veggie_chili', cuisine: 'latin', emoji: '🫘', meal: ['main'], time: 40, tags: ['spicy', 'batch', 'comfort'],
      name: { en: 'Sweet potato & bean chili', ro: 'Chili cu fasole și cartofi dulci' },
      ing: [['red_beans', 150], ['sweet_potato', 150], ['tomato_can', 150], ['onion', 50], ['bell_pepper', 70], ['chili', 5], ['cumin', 2], ['paprika', 2], ['olive_oil', 5]],
      steps: { en: ['Soften onion and pepper in oil, add spices and chili.', 'Add diced sweet potato, beans, tomatoes and 100 ml water per serving.', 'Simmer 25 minutes until the sweet potato is soft.'],
        ro: ['Călește ceapa și ardeiul, adaugă condimentele și ardeiul iute.', 'Adaugă cartoful dulce tăiat cuburi, fasolea, roșiile și 100 ml apă/porție.', 'Fierbe 25 de minute, până se înmoaie cartoful.'] } },
    { id: 'tofu_stirfry', cuisine: 'chinese', emoji: '🥢', meal: ['main'], time: 25, tags: ['spicy', 'quick'],
      name: { en: 'Crispy tofu & vegetable stir-fry', ro: 'Tofu crocant la wok cu legume' },
      ing: [['tofu', 150], ['broccoli', 100], ['bell_pepper', 80], ['carrot', 50], ['garlic', 5], ['chili', 5], ['soy_sauce', 15], ['olive_oil', 10], ['rice', 70, 'side']],
      steps: { en: ['Cook the rice. Cube tofu and fry until crispy.', 'Stir-fry vegetables, garlic and chili for 4 minutes.', 'Return tofu, add soy sauce. Serve over rice.'],
        ro: ['Fierbe orezul. Taie tofu cuburi și prăjește-l până devine crocant.', 'Călește legumele, usturoiul și ardeiul iute 4 minute.', 'Adaugă tofu și sosul de soia. Servește cu orez.'] } },
    { id: 'chickpea_quinoa_salad', cuisine: 'mediterranean', emoji: '🥙', meal: ['main'], time: 20, tags: ['fresh', 'mediterranean', 'quick'],
      name: { en: 'Chickpea & quinoa salad', ro: 'Salată cu năut și quinoa' },
      ing: [['quinoa', 60], ['chickpeas', 120], ['cucumber', 100], ['tomato', 100], ['parsley', 10], ['lemon', 20], ['olive_oil', 10]],
      steps: { en: ['Cook quinoa and let it cool.', 'Mix with chickpeas, chopped cucumber, tomato and parsley.', 'Dress with lemon juice, olive oil and salt.'],
        ro: ['Fierbe quinoa și las-o să se răcească.', 'Amestec-o cu năutul, castravetele, roșia și pătrunjelul tocate.', 'Asezonează cu zeamă de lămâie, ulei de măsline și sare.'] } },
    { id: 'tuna_salad', cuisine: 'mediterranean', emoji: '🥫', meal: ['main'], time: 15, tags: ['fresh', 'quick'],
      name: { en: 'Tuna salad with egg & olives', ro: 'Salată de ton cu ou și măsline' },
      ing: [['tuna_can', 120], ['lettuce', 80], ['cucumber', 100], ['tomato', 100], ['eggs', 1], ['olives', 20], ['lemon', 10], ['olive_oil', 10], ['bread', 50, 'side']],
      steps: { en: ['Hard-boil the egg (9 minutes).', 'Chop lettuce, cucumber and tomato; add drained tuna and olives.', 'Dress with lemon and oil. Top with the sliced egg.'],
        ro: ['Fierbe oul tare (9 minute).', 'Taie salata, castravetele și roșia; adaugă tonul scurs și măslinele.', 'Asezonează cu lămâie și ulei. Pune deasupra oul feliat.'] } },
    { id: 'iahnie_fasole', cuisine: 'eastern_european', emoji: '🥘', meal: ['main'], time: 90, tags: ['romanian', 'comfort', 'batch'],
      name: { en: 'Romanian white bean stew', ro: 'Iahnie de fasole' },
      ing: [['white_beans', 80], ['onion', 80], ['carrot', 50], ['garlic', 5], ['tomato_paste', 20], ['paprika', 2], ['olive_oil', 10], ['bread', 50, 'side']],
      steps: { en: ['Soak beans overnight, then boil 60 minutes until tender.', 'Fry onion and carrot, add garlic, paprika and tomato paste.', 'Add the beans with a little cooking water and simmer 15 minutes.', 'Serve with bread and pickles.'],
        ro: ['Pune fasolea la înmuiat peste noapte, apoi fierbe-o 60 de minute.', 'Călește ceapa și morcovul, adaugă usturoiul, boiaua și pasta de tomate.', 'Adaugă fasolea cu puțină apă de la fiert și fierbe 15 minute.', 'Servește cu pâine și murături.'] } },
    { id: 'tocanita_ciuperci', cuisine: 'eastern_european', emoji: '🍄', meal: ['main'], time: 35, tags: ['romanian', 'comfort'],
      name: { en: 'Mushroom stew with mămăligă', ro: 'Tocăniță de ciuperci cu mămăligă' },
      ing: [['mushrooms', 250], ['onion', 70], ['garlic', 5], ['tomato_paste', 15], ['olive_oil', 10], ['dill', 5], ['sour_cream', 30], ['cornmeal', 70, 'side']],
      steps: { en: ['Fry onion until soft, add sliced mushrooms and cook 10 minutes.', 'Add garlic, tomato paste and a splash of water; simmer 10 minutes.', 'Make mămăligă: whisk cornmeal into 300 ml boiling salted water, cook 15 minutes.', 'Serve with dill and sour cream.'],
        ro: ['Călește ceapa, adaugă ciupercile feliate și gătește 10 minute.', 'Adaugă usturoiul, pasta de tomate și puțină apă; fierbe 10 minute.', 'Mămăliga: mălaiul în 300 ml apă clocotită cu sare, 15 minute.', 'Servește cu mărar și smântână.'] } },
    { id: 'ardei_umpluti', cuisine: 'eastern_european', emoji: '🫑', meal: ['main'], time: 70, tags: ['romanian', 'comfort', 'batch'],
      name: { en: 'Stuffed peppers', ro: 'Ardei umpluți' },
      ing: [['bell_pepper', 200], ['ground_turkey', 100], ['rice', 30], ['onion', 40], ['dill', 5], ['tomato_can', 150], ['sour_cream', 30]],
      steps: { en: ['Mix meat, rice, chopped onion, dill and salt.', 'Fill the hollowed peppers and place them in a pot.', 'Cover with tomatoes and water and simmer 50 minutes.', 'Serve with sour cream.'],
        ro: ['Amestecă carnea, orezul, ceapa tocată, mărarul și sarea.', 'Umple ardeii curățați și așază-i într-o oală.', 'Acoperă cu roșii și apă și fierbe 50 de minute.', 'Servește cu smântână.'] } },
    { id: 'chicken_wrap', cuisine: 'middle_eastern', emoji: '🌯', meal: ['main'], time: 20, tags: ['quick', 'fresh'],
      name: { en: 'Chicken shawarma wrap', ro: 'Wrap cu pui shawarma' },
      ing: [['chicken_breast', 130], ['cumin', 1], ['paprika', 1], ['greek_yogurt', 50], ['garlic', 3], ['cucumber', 60], ['tomato', 60], ['lettuce', 30], ['tortilla', 1.5, 'side']],
      steps: { en: ['Season chicken strips with cumin, paprika and salt; pan-fry 8 minutes.', 'Mix yogurt with grated garlic and salt.', 'Fill tortillas with chicken, vegetables and garlic sauce.'],
        ro: ['Condimentează fâșiile de pui cu chimion, boia și sare; prăjește 8 minute.', 'Amestecă iaurtul cu usturoi ras și sare.', 'Umple lipiile cu pui, legume și sos de usturoi.'] } },
    { id: 'chicken_caesar', cuisine: 'western', emoji: '🥬', meal: ['main'], time: 20, tags: ['quick', 'fresh'],
      name: { en: 'Chicken Caesar-style salad', ro: 'Salată Caesar cu pui' },
      ing: [['chicken_breast', 150], ['lettuce', 120], ['parmesan', 15], ['eggs', 1], ['olive_oil', 15], ['lemon', 10], ['garlic', 2], ['bread', 30, 'side']],
      steps: { en: ['Grill the chicken and slice.', 'Whisk oil, lemon, grated garlic and half the parmesan into a dressing.', 'Toss with lettuce, top with chicken, boiled egg, croutons and parmesan.'],
        ro: ['Fă puiul la grătar și feliază-l.', 'Amestecă uleiul, lămâia, usturoiul ras și jumătate din parmezan.', 'Amestecă cu salata, adaugă puiul, oul fiert, crutoanele și parmezanul.'] } },
    { id: 'chiftele_dovlecei', cuisine: 'eastern_european', emoji: '🥒', meal: ['main'], time: 30, tags: ['romanian', 'fresh'],
      name: { en: 'Zucchini fritters with garlic yogurt', ro: 'Chiftele de dovlecei cu sos de iaurt' },
      ing: [['zucchini', 250], ['eggs', 1], ['telemea', 40], ['dill', 5], ['oats', 30], ['olive_oil', 10], ['greek_yogurt', 80], ['garlic', 3]],
      steps: { en: ['Grate zucchini, salt it and squeeze out the water.', 'Mix with egg, crumbled telemea, dill and blitzed oats.', 'Pan-fry spoonfuls 3 minutes per side.', 'Serve with yogurt mixed with garlic.'],
        ro: ['Rade dovleceii, sărează-i și stoarce apa.', 'Amestecă cu oul, telemeaua, mărarul și ovăzul măcinat.', 'Prăjește linguri de compoziție 3 minute pe fiecare parte.', 'Servește cu iaurt cu usturoi.'] } },
    { id: 'buddha_bowl', cuisine: 'international', emoji: '🍠', meal: ['main'], time: 35, tags: ['fresh'],
      name: { en: 'Sweet potato & hummus bowl', ro: 'Bol cu cartof dulce și hummus' },
      ing: [['sweet_potato', 200], ['chickpeas', 100], ['spinach', 50], ['hummus', 40], ['lemon', 10], ['olive_oil', 5], ['paprika', 1], ['quinoa', 50, 'side']],
      steps: { en: ['Roast cubed sweet potato and chickpeas with oil and paprika at 200 °C for 25 minutes.', 'Cook the quinoa.', 'Assemble with spinach, a spoon of hummus and lemon.'],
        ro: ['Coace cartoful dulce cuburi și năutul cu ulei și boia la 200 °C, 25 de minute.', 'Fierbe quinoa.', 'Asamblează cu spanac, hummus și lămâie.'] } },
    { id: 'varza_cu_pui', cuisine: 'eastern_european', emoji: '🥬', meal: ['main'], time: 45, tags: ['romanian', 'comfort', 'batch'],
      name: { en: 'Braised cabbage with chicken', ro: 'Varză călită cu pui' },
      ing: [['cabbage', 300], ['chicken_thigh', 150], ['onion', 40], ['tomato_paste', 15], ['paprika', 2], ['dill', 5], ['olive_oil', 10], ['bread', 40, 'side']],
      steps: { en: ['Brown the chicken pieces, remove.', 'Fry onion, add shredded cabbage and cook 10 minutes.', 'Add paprika, tomato paste, chicken and a little water; braise 25 minutes.', 'Finish with dill.'],
        ro: ['Rumenește bucățile de pui și scoate-le.', 'Călește ceapa, adaugă varza tocată și gătește 10 minute.', 'Adaugă boiaua, pasta de tomate, puiul și puțină apă; înăbușă 25 de minute.', 'Presară mărar.'] } },
    { id: 'broccoli_soup', cuisine: 'western', emoji: '🥦', meal: ['main'], time: 30, tags: ['comfort', 'quick'],
      name: { en: 'Creamy broccoli soup', ro: 'Supă cremă de broccoli' },
      ing: [['broccoli', 250], ['potato', 100], ['onion', 50], ['garlic', 5], ['olive_oil', 10], ['stock_cube', 0.25], ['almonds', 10], ['bread', 50, 'side']],
      steps: { en: ['Soften onion and garlic in oil.', 'Add broccoli, potato, the stock cube and 400 ml water per serving; boil 15 minutes.', 'Blend until smooth. Top with toasted almonds, serve with bread.'],
        ro: ['Călește ceapa și usturoiul.', 'Adaugă broccoli, cartoful, cubul și 400 ml apă/porție; fierbe 15 minute.', 'Pasează. Servește cu migdale prăjite și pâine.'] } },
    { id: 'salata_vinete', cuisine: 'eastern_european', emoji: '🍆', meal: ['main'], time: 40, tags: ['romanian', 'fresh'],
      name: { en: 'Romanian eggplant salad with tomatoes', ro: 'Salată de vinete cu roșii' },
      ing: [['eggplant', 300], ['onion', 30], ['olive_oil', 15], ['lemon', 10], ['tomato', 150], ['eggs', 1], ['bread', 70, 'side']],
      steps: { en: ['Roast eggplants over a flame or at 220 °C until charred, peel and drain.', 'Chop finely and beat with oil, lemon, salt and grated onion.', 'Serve with tomatoes, a boiled egg and bread.'],
        ro: ['Coace vinetele pe flacără sau la 220 °C, curăță-le și lasă-le la scurs.', 'Toacă-le și amestecă-le cu ulei, lămâie, sare și ceapă rasă.', 'Servește cu roșii, un ou fiert și pâine.'] } },

    // ───── world cuisines ─────
    { id: 'masala_omelette', cuisine: 'indian', emoji: '🍳', meal: ['breakfast'], time: 10, tags: ['quick', 'spicy'],
      name: { en: 'Masala omelette', ro: 'Omletă masala' },
      ing: [['eggs', 2], ['onion', 30], ['tomato', 50], ['chili', 3], ['cilantro', 3], ['turmeric', 0.5], ['olive_oil', 5], ['bread', 40, 'side']],
      steps: { en: ['Beat eggs with turmeric and salt.', 'Stir in finely chopped onion, tomato, chili and coriander.', 'Cook in a hot oiled pan 2 minutes per side. Serve with bread.'],
        ro: ['Bate ouăle cu turmeric și sare.', 'Adaugă ceapa, roșia, ardeiul iute și coriandrul tocate mărunt.', 'Gătește în tigaie încinsă 2 minute pe fiecare parte. Servește cu pâine.'] } },
    { id: 'huevos_rancheros', cuisine: 'latin', emoji: '🌮', meal: ['breakfast'], time: 15, tags: ['spicy'],
      name: { en: 'Huevos rancheros', ro: 'Huevos rancheros (ouă în stil mexican)' },
      ing: [['eggs', 2], ['tortilla_corn', 2, 'side'], ['black_beans', 80], ['tomato_can', 100], ['onion', 30], ['chili', 3], ['cilantro', 3], ['olive_oil', 5]],
      steps: { en: ['Simmer tomatoes, onion and chili for 5 minutes to make a quick salsa.', 'Warm the beans and the tortillas.', 'Fry the eggs and serve on the tortillas with beans, salsa and coriander.'],
        ro: ['Fierbe roșiile, ceapa și ardeiul iute 5 minute pentru o salsa rapidă.', 'Încălzește fasolea și tortillele.', 'Prăjește ouăle și servește-le pe tortille cu fasole, salsa și coriandru.'] } },
    { id: 'menemen', cuisine: 'middle_eastern', emoji: '🍅', meal: ['breakfast'], time: 15, tags: ['quick', 'mediterranean'],
      name: { en: 'Menemen (Turkish scrambled eggs)', ro: 'Menemen (ouă turcești cu roșii)' },
      ing: [['eggs', 2], ['tomato', 150], ['bell_pepper', 60], ['onion', 30], ['olive_oil', 7], ['chili_flakes', 0.5], ['bread', 40, 'side']],
      steps: { en: ['Soften onion and pepper in oil.', 'Add grated tomato and cook until saucy, about 5 minutes.', 'Stir in the beaten eggs gently until just set. Sprinkle chili flakes and serve with bread.'],
        ro: ['Călește ceapa și ardeiul în ulei.', 'Adaugă roșia rasă și gătește 5 minute, până se îngroașă.', 'Adaugă ouăle bătute și amestecă ușor până se închegă. Presară fulgi de ardei și servește cu pâine.'] } },
    { id: 'banana_pancakes', cuisine: 'western', emoji: '🥞', meal: ['breakfast'], time: 15, tags: ['sweet', 'quick'],
      name: { en: 'Banana oat pancakes', ro: 'Clătite din ovăz cu banană' },
      ing: [['oats', 50], ['banana', 100], ['eggs', 1], ['milk', 50], ['berries', 50], ['honey', 5]],
      steps: { en: ['Blend oats, banana, egg and milk into a batter.', 'Cook small pancakes in a non-stick pan, 2 minutes per side.', 'Serve with berries and honey.'],
        ro: ['Mixează ovăzul, banana, oul și laptele într-un aluat.', 'Coace clătite mici într-o tigaie antiaderentă, 2 minute pe fiecare parte.', 'Servește cu fructe de pădure și miere.'] } },
    { id: 'chana_masala', cuisine: 'indian', emoji: '🍛', meal: ['main'], time: 30, tags: ['spicy', 'batch', 'comfort'],
      name: { en: 'Chana masala (chickpea curry)', ro: 'Chana masala (curry de năut)' },
      ing: [['chickpeas', 200], ['onion', 70], ['tomato_can', 150], ['garlic', 5], ['ginger', 5], ['garam_masala', 2], ['turmeric', 1], ['cumin', 1], ['olive_oil', 10], ['cilantro', 5], ['rice', 60, 'side']],
      steps: { en: ['Fry onion until golden, add garlic, ginger and the spices for 1 minute.', 'Add tomatoes and chickpeas with a splash of water; simmer 15 minutes.', 'Finish with coriander and serve with rice.'],
        ro: ['Călește ceapa până se aurește, adaugă usturoiul, ghimbirul și condimentele 1 minut.', 'Adaugă roșiile și năutul cu puțină apă; fierbe 15 minute.', 'Presară coriandru și servește cu orez.'] } },
    { id: 'palak_paneer', cuisine: 'indian', emoji: '🥬', meal: ['main'], time: 30, tags: ['comfort'],
      name: { en: 'Palak paneer (spinach & paneer)', ro: 'Palak paneer (spanac cu paneer)' },
      ing: [['paneer', 100], ['spinach', 200], ['onion', 50], ['garlic', 5], ['ginger', 5], ['garam_masala', 2], ['greek_yogurt', 30], ['olive_oil', 5], ['rice', 60, 'side']],
      steps: { en: ['Wilt the spinach and blend it smooth.', 'Fry onion, garlic, ginger and garam masala, then add the spinach purée.', 'Stir in yogurt and cubed paneer; heat through 5 minutes. Serve with rice.'],
        ro: ['Opărește spanacul și pasează-l fin.', 'Călește ceapa, usturoiul, ghimbirul și garam masala, apoi adaugă piureul de spanac.', 'Adaugă iaurtul și paneerul tăiat cuburi; încălzește 5 minute. Servește cu orez.'] } },
    { id: 'tomato_egg_stirfry', cuisine: 'chinese', emoji: '🍅', meal: ['main'], time: 15, tags: ['quick', 'comfort'],
      name: { en: 'Tomato & egg stir-fry', ro: 'Ouă cu roșii la wok (stil chinezesc)' },
      ing: [['eggs', 2], ['tomato', 250], ['green_onion', 15], ['soy_sauce', 5], ['olive_oil', 8], ['rice', 70, 'side']],
      steps: { en: ['Scramble the eggs softly and set aside.', 'Stir-fry tomato wedges until juicy, add soy sauce and a pinch of sugar if you like.', 'Return the eggs, add spring onion and serve over rice.'],
        ro: ['Fă ouăle jumări moi și scoate-le.', 'Călește roșiile tăiate felii până lasă zeamă, adaugă sosul de soia.', 'Pune ouăle înapoi, adaugă ceapa verde și servește cu orez.'] } },
    { id: 'mapo_tofu', cuisine: 'chinese', emoji: '🌶️', meal: ['main'], time: 20, tags: ['spicy', 'quick'],
      name: { en: 'Mapo-style tofu with mushrooms', ro: 'Tofu mapo cu ciuperci' },
      ing: [['tofu', 200], ['mushrooms', 80], ['garlic', 5], ['ginger', 5], ['chili_flakes', 1], ['soy_sauce', 15], ['green_onion', 10], ['sesame_oil', 5], ['rice', 70, 'side']],
      steps: { en: ['Fry finely chopped mushrooms, garlic, ginger and chili until fragrant.', 'Add soy sauce, 100 ml water per serving and cubed tofu; simmer 5 minutes.', 'Drizzle sesame oil, top with spring onion and serve with rice.'],
        ro: ['Călește ciupercile tocate, usturoiul, ghimbirul și fulgii de ardei.', 'Adaugă sosul de soia, 100 ml apă/porție și tofu cuburi; fierbe 5 minute.', 'Stropește cu ulei de susan, presară ceapă verde și servește cu orez.'] } },
    { id: 'teriyaki_salmon', cuisine: 'japanese_korean', emoji: '🍣', meal: ['main'], time: 25, tags: ['quick'],
      name: { en: 'Teriyaki salmon with broccoli', ro: 'Somon teriyaki cu broccoli' },
      ing: [['salmon', 150], ['soy_sauce', 20], ['honey', 10], ['ginger', 5], ['broccoli', 150], ['rice', 70, 'side']],
      steps: { en: ['Mix soy sauce, honey and grated ginger.', 'Pan-fry the salmon 4 minutes per side, pour over the sauce and let it glaze.', 'Steam the broccoli and serve with rice.'],
        ro: ['Amestecă sosul de soia, mierea și ghimbirul ras.', 'Prăjește somonul 4 minute pe fiecare parte, toarnă sosul și lasă-l să se caramelizeze.', 'Fierbe broccoli la abur și servește cu orez.'] } },
    { id: 'miso_soup', cuisine: 'japanese_korean', emoji: '🍜', meal: ['main'], time: 15, tags: ['quick', 'comfort'],
      name: { en: 'Miso soup with tofu & greens', ro: 'Supă miso cu tofu și verdețuri' },
      ing: [['miso', 25], ['tofu', 100], ['spinach', 50], ['mushrooms', 50], ['green_onion', 10], ['rice', 70, 'side']],
      steps: { en: ['Simmer sliced mushrooms in 400 ml water per serving for 3 minutes.', 'Add tofu cubes and spinach, then turn off the heat.', 'Stir in the miso (never boil it). Top with spring onion; serve with rice.'],
        ro: ['Fierbe ciupercile feliate în 400 ml apă/porție 3 minute.', 'Adaugă tofu cuburi și spanacul, apoi stinge focul.', 'Dizolvă miso în supă (nu o mai fierbe). Presară ceapă verde; servește cu orez.'] } },
    { id: 'bibimbap', cuisine: 'japanese_korean', emoji: '🍚', meal: ['main'], time: 30, tags: ['spicy'],
      name: { en: 'Bibimbap (Korean rice bowl)', ro: 'Bibimbap (bol coreean cu orez)' },
      ing: [['ground_beef', 100], ['spinach', 80], ['carrot', 60], ['zucchini', 60], ['eggs', 1], ['gochujang', 15], ['sesame_oil', 5], ['garlic', 3], ['soy_sauce', 10], ['rice', 80, 'side']],
      steps: { en: ['Cook the rice. Brown the beef with garlic and soy sauce.', 'Quickly sauté the carrot, zucchini and spinach separately.', 'Arrange everything on rice, top with a fried egg, gochujang and sesame oil.'],
        ro: ['Fierbe orezul. Rumenește carnea cu usturoi și sos de soia.', 'Călește rapid, separat, morcovul, dovlecelul și spanacul.', 'Așază totul peste orez, adaugă un ou ochi, gochujang și ulei de susan.'] } },
    { id: 'thai_red_curry', cuisine: 'southeast_asian', emoji: '🍛', meal: ['main'], time: 25, tags: ['spicy', 'quick'],
      name: { en: 'Thai red curry with tofu', ro: 'Curry roșu thailandez cu tofu' },
      ing: [['tofu', 150], ['curry_paste', 20], ['coconut_milk', 120], ['bell_pepper', 80], ['zucchini', 80], ['lime', 10], ['cilantro', 5], ['rice', 60, 'side']],
      steps: { en: ['Fry the curry paste in a little coconut milk for 1 minute.', 'Add the rest of the coconut milk, sliced vegetables and tofu; simmer 10 minutes.', 'Finish with lime juice and coriander. Serve with rice.'],
        ro: ['Prăjește pasta de curry în puțin lapte de cocos 1 minut.', 'Adaugă restul laptelui de cocos, legumele feliate și tofu; fierbe 10 minute.', 'Stoarce lime și presară coriandru. Servește cu orez.'] } },
    { id: 'pad_thai', cuisine: 'southeast_asian', emoji: '🍤', meal: ['main'], time: 25, tags: ['quick'],
      name: { en: 'Shrimp pad thai', ro: 'Pad thai cu creveți' },
      ing: [['rice_noodles', 80], ['shrimp', 100], ['eggs', 1], ['peanuts', 15], ['green_onion', 15], ['lime', 15], ['soy_sauce', 15], ['garlic', 5], ['olive_oil', 10], ['chili_flakes', 0.5]],
      steps: { en: ['Soak the noodles in hot water for 8 minutes, drain.', 'Stir-fry garlic and shrimp 2 minutes, push aside and scramble the egg.', 'Add noodles, soy sauce and lime juice; toss. Top with peanuts, spring onion and chili.'],
        ro: ['Înmoaie tăițeii în apă fierbinte 8 minute, apoi scurge-i.', 'Călește usturoiul și creveții 2 minute, apoi fă oul jumări alături.', 'Adaugă tăițeii, sosul de soia și zeama de lime; amestecă. Presară arahide, ceapă verde și fulgi de ardei.'] } },
    { id: 'bun_noodle_salad', cuisine: 'southeast_asian', emoji: '🥗', meal: ['main'], time: 25, tags: ['fresh'],
      name: { en: 'Vietnamese chicken noodle salad', ro: 'Salată vietnameză cu tăiței și pui' },
      ing: [['rice_noodles', 70], ['chicken_breast', 120], ['lettuce', 50], ['cucumber', 80], ['carrot', 50], ['cilantro', 5], ['lime', 15], ['peanuts', 10], ['soy_sauce', 10], ['chili', 3]],
      steps: { en: ['Cook the noodles and rinse in cold water.', 'Grill or pan-fry the chicken and slice it.', 'Toss noodles with shredded vegetables and herbs; dress with lime, soy sauce and chili; top with chicken and peanuts.'],
        ro: ['Fierbe tăițeii și clătește-i cu apă rece.', 'Fă puiul la grătar sau în tigaie și feliază-l.', 'Amestecă tăițeii cu legumele tăiate fâșii și verdețurile; asezonează cu lime, sos de soia și ardei iute; adaugă puiul și arahidele.'] } },
    { id: 'black_bean_tacos', cuisine: 'latin', emoji: '🌮', meal: ['main'], time: 20, tags: ['quick', 'fresh'],
      name: { en: 'Black bean tacos', ro: 'Tacos cu fasole neagră' },
      ing: [['tortilla_corn', 3, 'side'], ['black_beans', 150], ['sweet_corn', 60], ['tomato', 80], ['avocado', 0.5], ['lime', 10], ['cilantro', 5], ['cumin', 1], ['cheddar', 20]],
      steps: { en: ['Warm the beans and corn with cumin and a splash of water; lightly mash.', 'Chop tomato and avocado with lime juice and coriander.', 'Fill warm tortillas with beans, salsa and grated cheese.'],
        ro: ['Încălzește fasolea și porumbul cu chimion și puțină apă; strivește ușor.', 'Taie roșia și avocado cu zeamă de lime și coriandru.', 'Umple tortillele calde cu fasole, salsa și brânză rasă.'] } },
    { id: 'burrito_bowl', cuisine: 'latin', emoji: '🥙', meal: ['main'], time: 30, tags: ['batch'],
      name: { en: 'Chicken burrito bowl', ro: 'Bol burrito cu pui' },
      ing: [['chicken_breast', 130], ['black_beans', 80], ['sweet_corn', 50], ['tomato', 80], ['lettuce', 40], ['lime', 10], ['cumin', 1], ['paprika', 1], ['greek_yogurt', 30], ['rice', 60, 'side']],
      steps: { en: ['Season the chicken with cumin, paprika and salt; pan-fry and slice.', 'Cook the rice; warm the beans and corn.', 'Build bowls with rice, chicken, beans, corn, tomato, lettuce, a spoon of yogurt and lime.'],
        ro: ['Condimentează puiul cu chimion, boia și sare; prăjește-l și feliază-l.', 'Fierbe orezul; încălzește fasolea și porumbul.', 'Asamblează boluri cu orez, pui, fasole, porumb, roșie, salată, o lingură de iaurt și lime.'] } },
    { id: 'turkish_lentil_soup', cuisine: 'middle_eastern', emoji: '🥣', meal: ['main'], time: 35, tags: ['comfort', 'batch'],
      name: { en: 'Turkish red lentil soup (mercimek)', ro: 'Supă turcească de linte roșie (mercimek)' },
      ing: [['lentils', 60], ['onion', 50], ['carrot', 50], ['potato', 50], ['tomato_paste', 10], ['cumin', 1], ['paprika', 1], ['lemon', 15], ['olive_oil', 7], ['bread', 40, 'side']],
      steps: { en: ['Soften onion and carrot in oil, add tomato paste and spices.', 'Add lentils, diced potato and 400 ml water per serving; simmer 20 minutes.', 'Blend smooth. Serve with lemon and bread.'],
        ro: ['Călește ceapa și morcovul, adaugă pasta de tomate și condimentele.', 'Adaugă lintea, cartoful cuburi și 400 ml apă/porție; fierbe 20 de minute.', 'Pasează fin. Servește cu lămâie și pâine.'] } },
    { id: 'falafel_bowl', cuisine: 'middle_eastern', emoji: '🧆', meal: ['main'], time: 35, tags: ['fresh'],
      name: { en: 'Baked falafel bowl with tahini', ro: 'Bol cu falafel la cuptor și tahini' },
      ing: [['chickpeas', 150], ['parsley', 10], ['garlic', 3], ['cumin', 2], ['oats', 20], ['tahini', 15], ['lemon', 10], ['cucumber', 80], ['tomato', 80], ['pita', 1, 'side']],
      steps: { en: ['Blitz chickpeas, parsley, garlic, cumin and oats; shape small patties.', 'Bake at 200 °C for 20 minutes, turning once.', 'Whisk tahini with lemon and water; serve with chopped salad and pita.'],
        ro: ['Mixează năutul, pătrunjelul, usturoiul, chimionul și ovăzul; formează chifteluțe.', 'Coace la 200 °C 20 de minute, întorcându-le o dată.', 'Amestecă tahini cu lămâie și apă; servește cu salată tocată și pita.'] } },
    { id: 'chicken_tagine', cuisine: 'african', emoji: '🍲', meal: ['main'], time: 50, tags: ['comfort', 'batch'],
      name: { en: 'Moroccan chicken tagine with couscous', ro: 'Tajine marocan cu pui și cuscus' },
      ing: [['chicken_thigh', 160], ['onion', 60], ['carrot', 80], ['chickpeas', 60], ['tomato_can', 100], ['cumin', 1], ['cinnamon', 0.5], ['paprika', 1], ['garlic', 5], ['olive_oil', 7], ['couscous', 60, 'side']],
      steps: { en: ['Brown the chicken, add onion, garlic and spices.', 'Add carrots, chickpeas, tomatoes and a little water; cover and simmer 35 minutes.', 'Pour boiling water over the couscous, cover 5 minutes, fluff and serve.'],
        ro: ['Rumenește puiul, adaugă ceapa, usturoiul și condimentele.', 'Adaugă morcovii, năutul, roșiile și puțină apă; acoperă și fierbe 35 de minute.', 'Toarnă apă clocotită peste cuscus, acoperă 5 minute, apoi afânează și servește.'] } },
    { id: 'jollof_rice', cuisine: 'african', emoji: '🍚', meal: ['main'], time: 50, tags: ['spicy', 'batch', 'comfort'],
      name: { en: 'Jollof rice with chicken', ro: 'Orez jollof cu pui' },
      ing: [['chicken_thigh', 130], ['rice', 80], ['tomato_can', 150], ['bell_pepper', 60], ['onion', 60], ['tomato_paste', 15], ['chili', 3], ['curry', 1], ['garlic', 3], ['olive_oil', 10], ['stock_cube', 0.25]],
      steps: { en: ['Blend tomatoes, pepper, half the onion and chili into a sauce.', 'Brown the chicken, fry the rest of the onion with tomato paste and curry, add the sauce and simmer 10 minutes.', 'Add washed rice, stock and 150 ml water per serving; cover tightly and cook on low 25 minutes.'],
        ro: ['Mixează roșiile, ardeiul, jumătate din ceapă și ardeiul iute într-un sos.', 'Rumenește puiul, călește restul de ceapă cu pasta de tomate și curry, adaugă sosul și fierbe 10 minute.', 'Adaugă orezul spălat, supa și 150 ml apă/porție; acoperă bine și gătește la foc mic 25 de minute.'] } },
    { id: 'sukuma_wiki', cuisine: 'african', emoji: '🥬', meal: ['main'], time: 30, tags: ['quick'],
      name: { en: 'Sukuma wiki with beans & ugali', ro: 'Sukuma wiki cu fasole și ugali' },
      ing: [['kale', 200], ['red_beans', 100], ['tomato', 100], ['onion', 50], ['olive_oil', 10], ['cornmeal', 80, 'side']],
      steps: { en: ['Make ugali: whisk maize flour into 250 ml boiling salted water per serving, stirring until very thick, 10 minutes.', 'Fry onion and tomato, add shredded greens and beans; cook 8 minutes.', 'Serve the greens with the ugali.'],
        ro: ['Ugali: adaugă mălaiul în 250 ml apă clocotită cu sare/porție, amestecând până devine foarte gros, 10 minute.', 'Călește ceapa și roșia, adaugă verdețurile tocate și fasolea; gătește 8 minute.', 'Servește verdețurile cu ugali.'] } },
    { id: 'red_red', cuisine: 'african', emoji: '🍌', meal: ['main'], time: 35, tags: ['comfort', 'spicy'],
      name: { en: 'Red-red (bean stew with fried plantain)', ro: 'Red-red (tocană de fasole cu plantain prăjit)' },
      ing: [['red_beans', 180], ['plantain', 150], ['onion', 50], ['tomato_can', 120], ['paprika', 1], ['chili', 3], ['olive_oil', 15]],
      steps: { en: ['Fry onion with paprika and chili, add tomatoes and simmer 10 minutes.', 'Add the beans and cook 10 more minutes.', 'Fry thick slices of ripe plantain until golden and serve alongside.'],
        ro: ['Călește ceapa cu boia și ardei iute, adaugă roșiile și fierbe 10 minute.', 'Adaugă fasolea și mai fierbe 10 minute.', 'Prăjește felii groase de plantain copt până se rumenesc și servește-le alături.'] } },
    { id: 'peanut_stew', cuisine: 'african', emoji: '🥜', meal: ['main'], time: 40, tags: ['comfort', 'batch', 'spicy'],
      name: { en: 'West African peanut stew (maafe)', ro: 'Tocană vest-africană cu arahide (maafe)' },
      ing: [['chicken_thigh', 130], ['peanut_butter', 25], ['tomato_can', 120], ['onion', 50], ['sweet_potato', 120], ['garlic', 3], ['ginger', 3], ['chili', 3], ['rice', 60, 'side']],
      steps: { en: ['Brown the chicken with onion, garlic and ginger.', 'Add tomatoes, cubed sweet potato, chili and water to cover; simmer 20 minutes.', 'Stir in the peanut butter and cook 5 more minutes. Serve with rice.'],
        ro: ['Rumenește puiul cu ceapa, usturoiul și ghimbirul.', 'Adaugă roșiile, cartoful dulce cuburi, ardeiul iute și apă cât să acopere; fierbe 20 de minute.', 'Adaugă untul de arahide și mai gătește 5 minute. Servește cu orez.'] } },
    { id: 'jacket_potato', cuisine: 'western', emoji: '🥔', meal: ['main'], time: 60, tags: ['comfort'],
      name: { en: 'Jacket potato with tuna & sweetcorn', ro: 'Cartof copt cu ton și porumb' },
      ing: [['potato', 300], ['tuna_can', 80], ['sweet_corn', 50], ['greek_yogurt', 40], ['lettuce', 40]],
      steps: { en: ['Prick the potato and bake at 200 °C for 50–60 minutes (or microwave 8 minutes, then bake 15).', 'Mix tuna, sweetcorn and yogurt with salt and pepper.', 'Split the potato, fill it and serve with salad.'],
        ro: ['Înțeapă cartoful și coace-l la 200 °C 50–60 de minute (sau 8 minute la microunde, apoi 15 la cuptor).', 'Amestecă tonul, porumbul și iaurtul cu sare și piper.', 'Despică cartoful, umple-l și servește cu salată.'] } },
    { id: 'minestrone', cuisine: 'italian', emoji: '🥣', meal: ['main'], time: 40, tags: ['comfort', 'batch'],
      name: { en: 'Minestrone', ro: 'Minestrone (supă italiană de legume)' },
      ing: [['white_beans', 40], ['pasta', 30], ['carrot', 50], ['zucchini', 80], ['potato', 60], ['tomato_can', 100], ['onion', 40], ['garlic', 3], ['stock_cube', 0.25], ['parmesan', 10], ['olive_oil', 5]],
      steps: { en: ['Soak the beans overnight and boil 50 minutes (or use 100 g canned beans).', 'Soften onion, carrot and garlic, add potato, zucchini, tomatoes, stock and 400 ml water per serving; simmer 15 minutes.', 'Add pasta and beans, cook 10 minutes. Serve with parmesan.'],
        ro: ['Înmoaie fasolea peste noapte și fierbe-o 50 de minute (sau folosește 100 g fasole la conservă).', 'Călește ceapa, morcovul și usturoiul, adaugă cartoful, dovlecelul, roșiile, supa și 400 ml apă/porție; fierbe 15 minute.', 'Adaugă pastele și fasolea, fierbe 10 minute. Servește cu parmezan.'] } },

    // ───── snacks ─────
    { id: 'apple_pb', cuisine: 'international', emoji: '🍎', meal: ['snack'], time: 2, tags: ['quick', 'sweet'],
      name: { en: 'Apple with peanut butter', ro: 'Măr cu unt de arahide' },
      ing: [['apple', 150], ['peanut_butter', 15]],
      steps: { en: ['Slice the apple and dip in peanut butter.'], ro: ['Feliază mărul și servește cu unt de arahide.'] } },
    { id: 'hummus_veggies', cuisine: 'middle_eastern', emoji: '🥕', meal: ['snack'], time: 5, tags: ['quick', 'fresh'],
      name: { en: 'Hummus with veggie sticks', ro: 'Hummus cu bețe de legume' },
      ing: [['hummus', 60], ['carrot', 80], ['cucumber', 80], ['bell_pepper', 60]],
      steps: { en: ['Cut vegetables into sticks and dip in hummus.'], ro: ['Taie legumele bețe și servește cu hummus.'] } },
    { id: 'banana_almonds', cuisine: 'international', emoji: '🥜', meal: ['snack'], time: 1, tags: ['quick', 'sweet'],
      name: { en: 'Banana & almonds', ro: 'Banană și migdale' },
      ing: [['banana', 120], ['almonds', 15]],
      steps: { en: ['Grab and go.'], ro: ['Gata de luat la pachet.'] } },
    { id: 'eggs_cucumber', cuisine: 'international', emoji: '🥚', meal: ['snack'], time: 10, tags: ['quick'],
      name: { en: 'Boiled eggs with cucumber', ro: 'Ouă fierte cu castravete' },
      ing: [['eggs', 2], ['cucumber', 100]],
      steps: { en: ['Boil eggs for 9 minutes, cool and peel.', 'Serve with sliced cucumber and a pinch of salt.'], ro: ['Fierbe ouăle 9 minute, răcește-le și curăță-le.', 'Servește cu castravete feliat și puțină sare.'] } },
    { id: 'cottage_berries', cuisine: 'international', emoji: '🫐', meal: ['snack'], time: 2, tags: ['quick', 'sweet'],
      name: { en: 'Cottage cheese with berries', ro: 'Brânză de vaci cu fructe de pădure' },
      ing: [['cottage', 150], ['berries', 60]],
      steps: { en: ['Top cottage cheese with thawed berries.'], ro: ['Pune fructele decongelate peste brânza de vaci.'] } },
    { id: 'roasted_chickpeas', cuisine: 'middle_eastern', emoji: '🫘', meal: ['snack'], time: 30, tags: ['quick'],
      name: { en: 'Crispy spiced chickpeas', ro: 'Năut crocant condimentat' },
      ing: [['chickpeas', 80], ['olive_oil', 5], ['paprika', 1], ['cumin', 0.5]],
      steps: { en: ['Pat chickpeas dry, toss with oil and spices.', 'Roast at 200 °C for 25 minutes, shaking halfway.'], ro: ['Usucă năutul, amestecă-l cu ulei și condimente.', 'Coace la 200 °C 25 de minute, scuturând tava la jumătate.'] } },
    { id: 'yogurt_walnuts', cuisine: 'international', emoji: '🍯', meal: ['snack'], time: 2, tags: ['quick', 'sweet'],
      name: { en: 'Yogurt with walnuts & honey', ro: 'Iaurt cu nuci și miere' },
      ing: [['greek_yogurt', 150], ['walnuts', 10], ['honey', 5]],
      steps: { en: ['Top yogurt with walnuts and honey.'], ro: ['Pune nucile și mierea peste iaurt.'] } },
  ];

  MP.CUISINES = ['international', 'eastern_european', 'mediterranean', 'italian', 'western', 'latin', 'middle_eastern',
    'african', 'indian', 'chinese', 'japanese_korean', 'southeast_asian'];

  MP.RECIPE_BY_ID = Object.fromEntries(MP.RECIPES.map((r) => [r.id, r]));
})(typeof window !== 'undefined' ? window : globalThis);
